<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Item;

class ItemSeeder extends Seeder
{
    public function run()
    {
        Item::create(['sub_escala_id' => '1','item' => 'A la pata coja']);
        Item::create(['sub_escala_id' => '1','item' => 'Tocar la nariz con el dedo']);
        Item::create(['sub_escala_id' => '1','item' => 'Estimulacion con los dedos, Derecha: 1-Corazon   2-Anular']);
        Item::create(['sub_escala_id' => '1','item' => 'Estimulacion con los dedos, Izquierda: 1-Pulgar   2-Anular']);
        Item::create(['sub_escala_id' => '1','item' => 'Estimulacion con los dedos, Derecha: 1-Meñique   2-Corazon  3-Pulgar']);
        Item::create(['sub_escala_id' => '1','item' => 'Estimulacion con los dedos, Izquierda: 1-Pulgar   2-Corazon  3-Meñique']);
        Item::create(['sub_escala_id' => '1','item' => 'Estimulacion con los dedos, Derecha: 1-Indice   2-Anular   3-Pulgar']);
        Item::create(['sub_escala_id' => '1','item' => 'Andar en equilibrio']);
        Item::create(['sub_escala_id' => '1','item' => 'Saltar con los pies juntos']);
        Item::create(['sub_escala_id' => '1','item' => 'En cunclillas con los brazon en cruz']);
        Item::create(['sub_escala_id' => '1','item' => 'Tocar con el pulgar todos los dedos de la mano']);
        Item::create(['sub_escala_id' => '2','item' => 'Rosa']);
        Item::create(['sub_escala_id' => '2','item' => 'Espada']);
        Item::create(['sub_escala_id' => '2','item' => 'Escalera']);
        Item::create(['sub_escala_id' => '2','item' => 'Almeja']);
        Item::create(['sub_escala_id' => '2','item' => 'Pardo']);
        Item::create(['sub_escala_id' => '2','item' => 'Ermita']);
        Item::create(['sub_escala_id' => '2','item' => 'Prudente']);
        Item::create(['sub_escala_id' => '2','item' => 'Cromo']);
        Item::create(['sub_escala_id' => '2','item' => 'Gracioso']);
        Item::create(['sub_escala_id' => '2','item' => 'Transparente']);
        Item::create(['sub_escala_id' => '2','item' => 'Dragon']);
        Item::create(['sub_escala_id' => '2','item' => 'Esterilidad']);
        Item::create(['sub_escala_id' => '2','item' => 'Influencia']);
        Item::create(['sub_escala_id' => '2','item' => 'Pradera']);
        Item::create(['sub_escala_id' => '2','item' => 'Entrada']);
        Item::create(['sub_escala_id' => '3','item' => 'En la fruteria venden peras verdes']);
        Item::create(['sub_escala_id' => '3','item' => 'El sol sale por detras de las montañasr']);
        Item::create(['sub_escala_id' => '3','item' => 'La estufa da mucho calor en el invierno']);
        Item::create(['sub_escala_id' => '3','item' => 'El jardinero planto rosas blancas y amarillas']);
        Item::create(['sub_escala_id' => '4','item' => '¿Como se llamaba la niña?']);
        Item::create(['sub_escala_id' => '4','item' => '¿Cuando fue al circo?']);
        Item::create(['sub_escala_id' => '4','item' => '¿Donde estaba el circo?']);
        Item::create(['sub_escala_id' => '4','item' => '¿Que llevaba el domador?']);
        Item::create(['sub_escala_id' => '4','item' => '¿Como eran los payasos?']);
        Item::create(['sub_escala_id' => '4','item' => '¿Que le paso a un trapecista?']);
        Item::create(['sub_escala_id' => '4','item' => '¿Que le compro su papá?']);
        Item::create(['sub_escala_id' => '4','item' => '¿Donde fue al terminar la función?']);
        Item::create(['sub_escala_id' => '4','item' => '¿Que fue lo que mas le gusto?']);
        Item::create(['sub_escala_id' => '5','item' => 'Pon el lapiz debajo de la mesa']);
        Item::create(['sub_escala_id' => '5','item' => 'Pon el lapiz encima del papel']);
        Item::create(['sub_escala_id' => '5','item' => 'Ponte delante de mi']);
        Item::create(['sub_escala_id' => '5','item' => 'Ponde detras de mi']);
        Item::create(['sub_escala_id' => '5','item' => 'Levanta la mano derecha']);
        Item::create(['sub_escala_id' => '5','item' => 'Levanta la mano izquierda']);
        Item::create(['sub_escala_id' => '5','item' => 'Con la mano derecha, tocate la oreja derecha']);
        Item::create(['sub_escala_id' => '5','item' => 'Con la mano izquierda, tapate el ojo izquierdo']);
        Item::create(['sub_escala_id' => '5','item' => 'Con la mano derecha, tocate la pierna izquierda']);
        Item::create(['sub_escala_id' => '5','item' => 'Con la mano izquierda, tocate la oreja derecha']);
        Item::create(['sub_escala_id' => '5','item' => 'Con tu mano derecha, tocame mi ojo izquierdo']);
        Item::create(['sub_escala_id' => '5','item' => 'Un cuadrado hacia la derecha (anexo 1)']);
        Item::create(['sub_escala_id' => '5','item' => 'Dos cuadrados hacia arriba (anexo 1)']);
        Item::create(['sub_escala_id' => '5','item' => 'Dos cuadrados hacia la izquierda (anexo 1)']);
        Item::create(['sub_escala_id' => '5','item' => 'Un cuadrado hacia abajo (anexo 1)']);
        Item::create(['sub_escala_id' => '6','item' => '1']);
        Item::create(['sub_escala_id' => '6','item' => '2']);
        Item::create(['sub_escala_id' => '6','item' => '3']);
        Item::create(['sub_escala_id' => '6','item' => '4']);
        Item::create(['sub_escala_id' => '6','item' => '5']);
        Item::create(['sub_escala_id' => '6','item' => '6']);
        Item::create(['sub_escala_id' => '6','item' => '7']);
        Item::create(['sub_escala_id' => '6','item' => '8']);
        Item::create(['sub_escala_id' => '6','item' => '9']);
        Item::create(['sub_escala_id' => '6','item' => '10']);
        Item::create(['sub_escala_id' => '6','item' => '11']);
        Item::create(['sub_escala_id' => '6','item' => '12']);
        Item::create(['sub_escala_id' => '6','item' => '13']);
        Item::create(['sub_escala_id' => '6','item' => '14']);
        Item::create(['sub_escala_id' => '6','item' => '15']);
        Item::create(['sub_escala_id' => '7','item' => 'Luna']);
        Item::create(['sub_escala_id' => '7','item' => 'Globos']);
        Item::create(['sub_escala_id' => '7','item' => 'Television']);
        Item::create(['sub_escala_id' => '7','item' => 'Lapicero']);
        Item::create(['sub_escala_id' => '7','item' => 'Bebe']);
        Item::create(['sub_escala_id' => '7','item' => 'Paraguas']);
        Item::create(['sub_escala_id' => '7','item' => 'Balon']);
        Item::create(['sub_escala_id' => '7','item' => 'Bicicleta']);
        Item::create(['sub_escala_id' => '7','item' => 'Casa']);
        Item::create(['sub_escala_id' => '7','item' => 'Perro']);
        Item::create(['sub_escala_id' => '8','item' => 'O-O-O-O']);
        Item::create(['sub_escala_id' => '8','item' => 'OO-OO-OO']);
        Item::create(['sub_escala_id' => '8','item' => 'O-OO-O-OO']);
        Item::create(['sub_escala_id' => '8','item' => 'O-O-O-OO']);
        Item::create(['sub_escala_id' => '8','item' => 'OO-O-O-OO']);
        Item::create(['sub_escala_id' => '8','item' => 'OO-O-OOO']);
        Item::create(['sub_escala_id' => '8','item' => 'OOO-O-O-OO']);
        Item::create(['sub_escala_id' => '9','item' => 'Coche']);
        Item::create(['sub_escala_id' => '9','item' => 'Arbol']);
        Item::create(['sub_escala_id' => '9','item' => 'Barco-Mar']);
        Item::create(['sub_escala_id' => '9','item' => 'Tigre-Television']);
        Item::create(['sub_escala_id' => '10','item' => 'Numero total de cuadros marcados']);
        Item::create(['sub_escala_id' => '10','item' => 'Numro total de otras figuras marcadas']);
        Item::create(['sub_escala_id' => '11','item' => 'Mula']);
        Item::create(['sub_escala_id' => '11','item' => 'Loba']);
        Item::create(['sub_escala_id' => '11','item' => 'Zapato']);
        Item::create(['sub_escala_id' => '11','item' => 'Sol']);
        Item::create(['sub_escala_id' => '11','item' => 'Pinza']);
        Item::create(['sub_escala_id' => '11','item' => 'Cajon']);
        Item::create(['sub_escala_id' => '11','item' => 'Globo']);
        Item::create(['sub_escala_id' => '11','item' => 'Fruta']);
        Item::create(['sub_escala_id' => '11','item' => 'Prisa']);
        Item::create(['sub_escala_id' => '11','item' => 'Truco']);
        Item::create(['sub_escala_id' => '11','item' => 'La luna sale de noche']);
        Item::create(['sub_escala_id' => '11','item' => 'La espiga de trigo']);
        Item::create(['sub_escala_id' => '12','item' => 'Mula']);
        Item::create(['sub_escala_id' => '12','item' => 'Loba']);
        Item::create(['sub_escala_id' => '12','item' => 'Zapato']);
        Item::create(['sub_escala_id' => '12','item' => 'Sol']);
        Item::create(['sub_escala_id' => '12','item' => 'Pinza']);
        Item::create(['sub_escala_id' => '12','item' => 'Cajon']);
        Item::create(['sub_escala_id' => '12','item' => 'Globo']);
        Item::create(['sub_escala_id' => '12','item' => 'Fruta']);
        Item::create(['sub_escala_id' => '12','item' => 'Prisa']);
        Item::create(['sub_escala_id' => '12','item' => 'Truco']);
        Item::create(['sub_escala_id' => '12','item' => 'La luna sale de noche']);
        Item::create(['sub_escala_id' => '12','item' => 'La espiga de trigo']);
        Item::create(['sub_escala_id' => '17','item' => 'Cabeza']);
        Item::create(['sub_escala_id' => '17','item' => 'Ojos']);
        Item::create(['sub_escala_id' => '17','item' => 'Nariz']);
        Item::create(['sub_escala_id' => '17','item' => 'Boca']);
        Item::create(['sub_escala_id' => '17','item' => 'Cuerpo']);
        Item::create(['sub_escala_id' => '17','item' => 'Piernas']);
        Item::create(['sub_escala_id' => '17','item' => 'Brazos']);
        Item::create(['sub_escala_id' => '17','item' => 'pies']);
        Item::create(['sub_escala_id' => '17','item' => 'Rodilla']);
        Item::create(['sub_escala_id' => '17','item' => 'Perfil']);
        Item::create(['sub_escala_id' => '17','item' => 'Codo']);
        Item::create(['sub_escala_id' => '17','item' => 'Dos Labios']);
        Item::create(['sub_escala_id' => '17','item' => 'Fosas Nasales']);
        Item::create(['sub_escala_id' => '17','item' => 'Proporciones']);
        Item::create(['sub_escala_id' => '17','item' => 'Braz. u. Homb.']);
        Item::create(['sub_escala_id' => '17','item' => 'Ropa: 4 prendas']);
        Item::create(['sub_escala_id' => '17','item' => 'Pies 2']);
        Item::create(['sub_escala_id' => '17','item' => 'Cinco dedos']);
        Item::create(['sub_escala_id' => '17','item' => 'Pupilas']);
    }
}
