<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Municipio;

class MunicipioTableSeeder extends Seeder
{

	public function run()
	{
		/* MUNICIPIOS */
		Municipio::create(array('id' => 1, 'estado_id' => 1, 'municipio' => 'Alto Orinoco'));
		Municipio::create(array('id' => 2, 'estado_id' => 1, 'municipio' => 'Atabapo'));
		Municipio::create(array('id' => 3, 'estado_id' => 1, 'municipio' => 'Atures'));
		Municipio::create(array('id' => 4, 'estado_id' => 1, 'municipio' => 'Autana'));
		Municipio::create(array('id' => 5, 'estado_id' => 1, 'municipio' => 'Manapiare'));
		Municipio::create(array('id' => 6, 'estado_id' => 1, 'municipio' => 'Maroa'));
		Municipio::create(array('id' => 7, 'estado_id' => 1, 'municipio' => 'Río Negro'));
		Municipio::create(array('id' => 8, 'estado_id' => 2, 'municipio' => 'Anaco'));
		Municipio::create(array('id' => 9, 'estado_id' => 2, 'municipio' => 'Aragua'));
		Municipio::create(array('id' => 10, 'estado_id' => 2, 'municipio' => 'Manuel Ezequiel Bruzual'));
		Municipio::create(array('id' => 11, 'estado_id' => 2, 'municipio' => 'Diego Bautista Urbaneja'));
		Municipio::create(array('id' => 12, 'estado_id' => 2, 'municipio' => 'Fernando Peñalver'));
		Municipio::create(array('id' => 13, 'estado_id' => 2, 'municipio' => 'Francisco Del Carmen Carvajal'));
		Municipio::create(array('id' => 14, 'estado_id' => 2, 'municipio' => 'General Sir Arthur McGregor'));
		Municipio::create(array('id' => 15, 'estado_id' => 2, 'municipio' => 'Guanta'));
		Municipio::create(array('id' => 16, 'estado_id' => 2, 'municipio' => 'Independencia'));
		Municipio::create(array('id' => 17, 'estado_id' => 2, 'municipio' => 'José Gregorio Monagas'));
		Municipio::create(array('id' => 18, 'estado_id' => 2, 'municipio' => 'Juan Antonio Sotillo'));
		Municipio::create(array('id' => 19, 'estado_id' => 2, 'municipio' => 'Juan Manuel Cajigal'));
		Municipio::create(array('id' => 20, 'estado_id' => 2, 'municipio' => 'Libertad'));
		Municipio::create(array('id' => 21, 'estado_id' => 2, 'municipio' => 'Francisco de Miranda'));
		Municipio::create(array('id' => 22, 'estado_id' => 2, 'municipio' => 'Pedro María Freites'));
		Municipio::create(array('id' => 23, 'estado_id' => 2, 'municipio' => 'Píritu'));
		Municipio::create(array('id' => 24, 'estado_id' => 2, 'municipio' => 'San José de Guanipa'));
		Municipio::create(array('id' => 25, 'estado_id' => 2, 'municipio' => 'San Juan de Capistrano'));
		Municipio::create(array('id' => 26, 'estado_id' => 2, 'municipio' => 'Santa Ana'));
		Municipio::create(array('id' => 27, 'estado_id' => 2, 'municipio' => 'Simón Bolívar'));
		Municipio::create(array('id' => 28, 'estado_id' => 2, 'municipio' => 'Simón Rodríguez'));
		Municipio::create(array('id' => 29, 'estado_id' => 3, 'municipio' => 'Achaguas'));
		Municipio::create(array('id' => 30, 'estado_id' => 3, 'municipio' => 'Biruaca'));
		Municipio::create(array('id' => 31, 'estado_id' => 3, 'municipio' => 'Muñóz'));
		Municipio::create(array('id' => 32, 'estado_id' => 3, 'municipio' => 'Páez'));
		Municipio::create(array('id' => 33, 'estado_id' => 3, 'municipio' => 'Pedro Camejo'));
		Municipio::create(array('id' => 34, 'estado_id' => 3, 'municipio' => 'Rómulo Gallegos'));
		Municipio::create(array('id' => 35, 'estado_id' => 3, 'municipio' => 'San Fernando'));
		Municipio::create(array('id' => 36, 'estado_id' => 4, 'municipio' => 'Atanasio Girardot'));
		Municipio::create(array('id' => 37, 'estado_id' => 4, 'municipio' => 'Bolívar'));
		Municipio::create(array('id' => 38, 'estado_id' => 4, 'municipio' => 'Camatagua'));
		Municipio::create(array('id' => 39, 'estado_id' => 4, 'municipio' => 'Francisco Linares Alcántara'));
		Municipio::create(array('id' => 40, 'estado_id' => 4, 'municipio' => 'José Ángel Lamas'));
		Municipio::create(array('id' => 41, 'estado_id' => 4, 'municipio' => 'José Félix Ribas'));
		Municipio::create(array('id' => 42, 'estado_id' => 4, 'municipio' => 'José Rafael Revenga'));
		Municipio::create(array('id' => 43, 'estado_id' => 4, 'municipio' => 'Libertador'));
		Municipio::create(array('id' => 44, 'estado_id' => 4, 'municipio' => 'Mario Briceño Iragorry'));
		Municipio::create(array('id' => 45, 'estado_id' => 4, 'municipio' => 'Ocumare de la Costa de Oro'));
		Municipio::create(array('id' => 46, 'estado_id' => 4, 'municipio' => 'San Casimiro'));
		Municipio::create(array('id' => 47, 'estado_id' => 4, 'municipio' => 'San Sebastián'));
		Municipio::create(array('id' => 48, 'estado_id' => 4, 'municipio' => 'Santiago Mariño'));
		Municipio::create(array('id' => 49, 'estado_id' => 4, 'municipio' => 'Santos Michelena'));
		Municipio::create(array('id' => 50, 'estado_id' => 4, 'municipio' => 'Sucre'));
		Municipio::create(array('id' => 51, 'estado_id' => 4, 'municipio' => 'Tovar'));
		Municipio::create(array('id' => 52, 'estado_id' => 4, 'municipio' => 'Urdaneta'));
		Municipio::create(array('id' => 53, 'estado_id' => 4, 'municipio' => 'Zamora'));
		Municipio::create(array('id' => 54, 'estado_id' => 5, 'municipio' => 'Alberto Arvelo Torrealba'));
		Municipio::create(array('id' => 55, 'estado_id' => 5, 'municipio' => 'Andrés Eloy Blanco'));
		Municipio::create(array('id' => 56, 'estado_id' => 5, 'municipio' => 'Antonio José de Sucre'));
		Municipio::create(array('id' => 57, 'estado_id' => 5, 'municipio' => 'Arismendi'));
		Municipio::create(array('id' => 58, 'estado_id' => 5, 'municipio' => 'Barinas'));
		Municipio::create(array('id' => 59, 'estado_id' => 5, 'municipio' => 'Bolívar'));
		Municipio::create(array('id' => 60, 'estado_id' => 5, 'municipio' => 'Cruz Paredes'));
		Municipio::create(array('id' => 61, 'estado_id' => 5, 'municipio' => 'Ezequiel Zamora'));
		Municipio::create(array('id' => 62, 'estado_id' => 5, 'municipio' => 'Obispos'));
		Municipio::create(array('id' => 63, 'estado_id' => 5, 'municipio' => 'Pedraza'));
		Municipio::create(array('id' => 64, 'estado_id' => 5, 'municipio' => 'Rojas'));
		Municipio::create(array('id' => 65, 'estado_id' => 5, 'municipio' => 'Sosa'));
		Municipio::create(array('id' => 66, 'estado_id' => 6, 'municipio' => 'Caroní'));
		Municipio::create(array('id' => 67, 'estado_id' => 6, 'municipio' => 'Cedeño'));
		Municipio::create(array('id' => 68, 'estado_id' => 6, 'municipio' => 'El Callao'));
		Municipio::create(array('id' => 69, 'estado_id' => 6, 'municipio' => 'Gran Sabana'));
		Municipio::create(array('id' => 70, 'estado_id' => 6, 'municipio' => 'Heres'));
		Municipio::create(array('id' => 71, 'estado_id' => 6, 'municipio' => 'Piar'));
		Municipio::create(array('id' => 72, 'estado_id' => 6, 'municipio' => 'Angostura (Raúl Leoni)'));
		Municipio::create(array('id' => 73, 'estado_id' => 6, 'municipio' => 'Roscio'));
		Municipio::create(array('id' => 74, 'estado_id' => 6, 'municipio' => 'Sifontes'));
		Municipio::create(array('id' => 75, 'estado_id' => 6, 'municipio' => 'Sucre'));
		Municipio::create(array('id' => 76, 'estado_id' => 6, 'municipio' => 'Padre Pedro Chien'));
		Municipio::create(array('id' => 77, 'estado_id' => 7, 'municipio' => 'Bejuma'));
		Municipio::create(array('id' => 78, 'estado_id' => 7, 'municipio' => 'Carlos Arvelo'));
		Municipio::create(array('id' => 79, 'estado_id' => 7, 'municipio' => 'Diego Ibarra'));
		Municipio::create(array('id' => 80, 'estado_id' => 7, 'municipio' => 'Guacara'));
		Municipio::create(array('id' => 81, 'estado_id' => 7, 'municipio' => 'Juan José Mora'));
		Municipio::create(array('id' => 82, 'estado_id' => 7, 'municipio' => 'Libertador'));
		Municipio::create(array('id' => 83, 'estado_id' => 7, 'municipio' => 'Los Guayos'));
		Municipio::create(array('id' => 84, 'estado_id' => 7, 'municipio' => 'Miranda'));
		Municipio::create(array('id' => 85, 'estado_id' => 7, 'municipio' => 'Montalbán'));
		Municipio::create(array('id' => 86, 'estado_id' => 7, 'municipio' => 'Naguanagua'));
		Municipio::create(array('id' => 87, 'estado_id' => 7, 'municipio' => 'Puerto Cabello'));
		Municipio::create(array('id' => 88, 'estado_id' => 7, 'municipio' => 'San Diego'));
		Municipio::create(array('id' => 89, 'estado_id' => 7, 'municipio' => 'San Joaquín'));
		Municipio::create(array('id' => 90, 'estado_id' => 7, 'municipio' => 'Valencia'));
		Municipio::create(array('id' => 91, 'estado_id' => 8, 'municipio' => 'Anzoátegui'));
		Municipio::create(array('id' => 92, 'estado_id' => 8, 'municipio' => 'Tinaquillo'));
		Municipio::create(array('id' => 93, 'estado_id' => 8, 'municipio' => 'Girardot'));
		Municipio::create(array('id' => 94, 'estado_id' => 8, 'municipio' => 'Lima Blanco'));
		Municipio::create(array('id' => 95, 'estado_id' => 8, 'municipio' => 'Pao de San Juan Bautista'));
		Municipio::create(array('id' => 96, 'estado_id' => 8, 'municipio' => 'Ricaurte'));
		Municipio::create(array('id' => 97, 'estado_id' => 8, 'municipio' => 'Rómulo Gallegos'));
		Municipio::create(array('id' => 98, 'estado_id' => 8, 'municipio' => 'San Carlos'));
		Municipio::create(array('id' => 99, 'estado_id' => 8, 'municipio' => 'Tinaco'));
		Municipio::create(array('id' => 100, 'estado_id' => 9, 'municipio' => 'Antonio Díaz'));
		Municipio::create(array('id' => 101, 'estado_id' => 9, 'municipio' => 'Casacoima'));
		Municipio::create(array('id' => 102, 'estado_id' => 9, 'municipio' => 'Pedernales'));
		Municipio::create(array('id' => 103, 'estado_id' => 9, 'municipio' => 'Tucupita'));
		Municipio::create(array('id' => 104, 'estado_id' => 10, 'municipio' => 'Acosta'));
		Municipio::create(array('id' => 105, 'estado_id' => 10, 'municipio' => 'Bolívar'));
		Municipio::create(array('id' => 106, 'estado_id' => 10, 'municipio' => 'Buchivacoa'));
		Municipio::create(array('id' => 107, 'estado_id' => 10, 'municipio' => 'Cacique Manaure'));
		Municipio::create(array('id' => 108, 'estado_id' => 10, 'municipio' => 'Carirubana'));
		Municipio::create(array('id' => 109, 'estado_id' => 10, 'municipio' => 'Colina'));
		Municipio::create(array('id' => 110, 'estado_id' => 10, 'municipio' => 'Dabajuro'));
		Municipio::create(array('id' => 111, 'estado_id' => 10, 'municipio' => 'Democracia'));
		Municipio::create(array('id' => 112, 'estado_id' => 10, 'municipio' => 'Falcón'));
		Municipio::create(array('id' => 113, 'estado_id' => 10, 'municipio' => 'Federación'));
		Municipio::create(array('id' => 114, 'estado_id' => 10, 'municipio' => 'Jacura'));
		Municipio::create(array('id' => 115, 'estado_id' => 10, 'municipio' => 'José Laurencio Silva'));
		Municipio::create(array('id' => 116, 'estado_id' => 10, 'municipio' => 'Los Taques'));
		Municipio::create(array('id' => 117, 'estado_id' => 10, 'municipio' => 'Mauroa'));
		Municipio::create(array('id' => 118, 'estado_id' => 10, 'municipio' => 'Miranda'));
		Municipio::create(array('id' => 119, 'estado_id' => 10, 'municipio' => 'Monseñor Iturriza'));
		Municipio::create(array('id' => 120, 'estado_id' => 10, 'municipio' => 'Palmasola'));
		Municipio::create(array('id' => 121, 'estado_id' => 10, 'municipio' => 'Petit'));
		Municipio::create(array('id' => 122, 'estado_id' => 10, 'municipio' => 'Píritu'));
		Municipio::create(array('id' => 123, 'estado_id' => 10, 'municipio' => 'San Francisco'));
		Municipio::create(array('id' => 124, 'estado_id' => 10, 'municipio' => 'Sucre'));
		Municipio::create(array('id' => 125, 'estado_id' => 10, 'municipio' => 'Tocópero'));
		Municipio::create(array('id' => 126, 'estado_id' => 10, 'municipio' => 'Unión'));
		Municipio::create(array('id' => 127, 'estado_id' => 10, 'municipio' => 'Urumaco'));
		Municipio::create(array('id' => 128, 'estado_id' => 10, 'municipio' => 'Zamora'));
		Municipio::create(array('id' => 129, 'estado_id' => 11, 'municipio' => 'Camaguán'));
		Municipio::create(array('id' => 130, 'estado_id' => 11, 'municipio' => 'Chaguaramas'));
		Municipio::create(array('id' => 131, 'estado_id' => 11, 'municipio' => 'El Socorro'));
		Municipio::create(array('id' => 132, 'estado_id' => 11, 'municipio' => 'José Félix Ribas'));
		Municipio::create(array('id' => 133, 'estado_id' => 11, 'municipio' => 'José Tadeo Monagas'));
		Municipio::create(array('id' => 134, 'estado_id' => 11, 'municipio' => 'Juan Germán Roscio'));
		Municipio::create(array('id' => 135, 'estado_id' => 11, 'municipio' => 'Julián Mellado'));
		Municipio::create(array('id' => 136, 'estado_id' => 11, 'municipio' => 'Las Mercedes'));
		Municipio::create(array('id' => 137, 'estado_id' => 11, 'municipio' => 'Leonardo Infante'));
		Municipio::create(array('id' => 138, 'estado_id' => 11, 'municipio' => 'Pedro Zaraza'));
		Municipio::create(array('id' => 139, 'estado_id' => 11, 'municipio' => 'Ortíz'));
		Municipio::create(array('id' => 140, 'estado_id' => 11, 'municipio' => 'San Gerónimo de Guayabal'));
		Municipio::create(array('id' => 141, 'estado_id' => 11, 'municipio' => 'San José de Guaribe'));
		Municipio::create(array('id' => 142, 'estado_id' => 11, 'municipio' => 'Santa María de Ipire'));
		Municipio::create(array('id' => 143, 'estado_id' => 11, 'municipio' => 'Sebastián Francisco de Miranda'));
		Municipio::create(array('id' => 144, 'estado_id' => 12, 'municipio' => 'Andrés Eloy Blanco'));
		Municipio::create(array('id' => 145, 'estado_id' => 12, 'municipio' => 'Crespo'));
		Municipio::create(array('id' => 146, 'estado_id' => 12, 'municipio' => 'Iribarren'));
		Municipio::create(array('id' => 147, 'estado_id' => 12, 'municipio' => 'Jiménez'));
		Municipio::create(array('id' => 148, 'estado_id' => 12, 'municipio' => 'Morán'));
		Municipio::create(array('id' => 149, 'estado_id' => 12, 'municipio' => 'Palavecino'));
		Municipio::create(array('id' => 150, 'estado_id' => 12, 'municipio' => 'Simón Planas'));
		Municipio::create(array('id' => 151, 'estado_id' => 12, 'municipio' => 'Torres'));
		Municipio::create(array('id' => 152, 'estado_id' => 12, 'municipio' => 'Urdaneta'));
		Municipio::create(array('id' => 179, 'estado_id' => 13, 'municipio' => 'Alberto Adriani'));
		Municipio::create(array('id' => 180, 'estado_id' => 13, 'municipio' => 'Andrés Bello'));
		Municipio::create(array('id' => 181, 'estado_id' => 13, 'municipio' => 'Antonio Pinto Salinas'));
		Municipio::create(array('id' => 182, 'estado_id' => 13, 'municipio' => 'Aricagua'));
		Municipio::create(array('id' => 183, 'estado_id' => 13, 'municipio' => 'Arzobispo Chacón'));
		Municipio::create(array('id' => 184, 'estado_id' => 13, 'municipio' => 'Campo Elías'));
		Municipio::create(array('id' => 185, 'estado_id' => 13, 'municipio' => 'Caracciolo Parra Olmedo'));
		Municipio::create(array('id' => 186, 'estado_id' => 13, 'municipio' => 'Cardenal Quintero'));
		Municipio::create(array('id' => 187, 'estado_id' => 13, 'municipio' => 'Guaraque'));
		Municipio::create(array('id' => 188, 'estado_id' => 13, 'municipio' => 'Julio César Salas'));
		Municipio::create(array('id' => 189, 'estado_id' => 13, 'municipio' => 'Justo Briceño'));
		Municipio::create(array('id' => 190, 'estado_id' => 13, 'municipio' => 'Libertador'));
		Municipio::create(array('id' => 191, 'estado_id' => 13, 'municipio' => 'Miranda'));
		Municipio::create(array('id' => 192, 'estado_id' => 13, 'municipio' => 'Obispo Ramos de Lora'));
		Municipio::create(array('id' => 193, 'estado_id' => 13, 'municipio' => 'Padre Noguera'));
		Municipio::create(array('id' => 194, 'estado_id' => 13, 'municipio' => 'Pueblo Llano'));
		Municipio::create(array('id' => 195, 'estado_id' => 13, 'municipio' => 'Rangel'));
		Municipio::create(array('id' => 196, 'estado_id' => 13, 'municipio' => 'Rivas Dávila'));
		Municipio::create(array('id' => 197, 'estado_id' => 13, 'municipio' => 'Santos Marquina'));
		Municipio::create(array('id' => 198, 'estado_id' => 13, 'municipio' => 'Sucre'));
		Municipio::create(array('id' => 199, 'estado_id' => 13, 'municipio' => 'Tovar'));
		Municipio::create(array('id' => 200, 'estado_id' => 13, 'municipio' => 'Tulio Febres Cordero'));
		Municipio::create(array('id' => 201, 'estado_id' => 13, 'municipio' => 'Zea'));
		Municipio::create(array('id' => 223, 'estado_id' => 14, 'municipio' => 'Acevedo'));
		Municipio::create(array('id' => 224, 'estado_id' => 14, 'municipio' => 'Andrés Bello'));
		Municipio::create(array('id' => 225, 'estado_id' => 14, 'municipio' => 'Baruta'));
		Municipio::create(array('id' => 226, 'estado_id' => 14, 'municipio' => 'Brión'));
		Municipio::create(array('id' => 227, 'estado_id' => 14, 'municipio' => 'Buroz'));
		Municipio::create(array('id' => 228, 'estado_id' => 14, 'municipio' => 'Carrizal'));
		Municipio::create(array('id' => 229, 'estado_id' => 14, 'municipio' => 'Chacao'));
		Municipio::create(array('id' => 230, 'estado_id' => 14, 'municipio' => 'Cristóbal Rojas'));
		Municipio::create(array('id' => 231, 'estado_id' => 14, 'municipio' => 'El Hatillo'));
		Municipio::create(array('id' => 232, 'estado_id' => 14, 'municipio' => 'Guaicaipuro'));
		Municipio::create(array('id' => 233, 'estado_id' => 14, 'municipio' => 'Independencia'));
		Municipio::create(array('id' => 234, 'estado_id' => 14, 'municipio' => 'Lander'));
		Municipio::create(array('id' => 235, 'estado_id' => 14, 'municipio' => 'Los Salias'));
		Municipio::create(array('id' => 236, 'estado_id' => 14, 'municipio' => 'Páez'));
		Municipio::create(array('id' => 237, 'estado_id' => 14, 'municipio' => 'Paz Castillo'));
		Municipio::create(array('id' => 238, 'estado_id' => 14, 'municipio' => 'Pedro Gual'));
		Municipio::create(array('id' => 239, 'estado_id' => 14, 'municipio' => 'Plaza'));
		Municipio::create(array('id' => 240, 'estado_id' => 14, 'municipio' => 'Simón Bolívar'));
		Municipio::create(array('id' => 241, 'estado_id' => 14, 'municipio' => 'Sucre'));
		Municipio::create(array('id' => 242, 'estado_id' => 14, 'municipio' => 'Urdaneta'));
		Municipio::create(array('id' => 243, 'estado_id' => 14, 'municipio' => 'Zamora'));
		Municipio::create(array('id' => 258, 'estado_id' => 15, 'municipio' => 'Acosta'));
		Municipio::create(array('id' => 259, 'estado_id' => 15, 'municipio' => 'Aguasay'));
		Municipio::create(array('id' => 260, 'estado_id' => 15, 'municipio' => 'Bolívar'));
		Municipio::create(array('id' => 261, 'estado_id' => 15, 'municipio' => 'Caripe'));
		Municipio::create(array('id' => 262, 'estado_id' => 15, 'municipio' => 'Cedeño'));
		Municipio::create(array('id' => 263, 'estado_id' => 15, 'municipio' => 'Ezequiel Zamora'));
		Municipio::create(array('id' => 264, 'estado_id' => 15, 'municipio' => 'Libertador'));
		Municipio::create(array('id' => 265, 'estado_id' => 15, 'municipio' => 'Maturín'));
		Municipio::create(array('id' => 266, 'estado_id' => 15, 'municipio' => 'Piar'));
		Municipio::create(array('id' => 267, 'estado_id' => 15, 'municipio' => 'Punceres'));
		Municipio::create(array('id' => 268, 'estado_id' => 15, 'municipio' => 'Santa Bárbara'));
		Municipio::create(array('id' => 269, 'estado_id' => 15, 'municipio' => 'Sotillo'));
		Municipio::create(array('id' => 270, 'estado_id' => 15, 'municipio' => 'Uracoa'));
		Municipio::create(array('id' => 271, 'estado_id' => 16, 'municipio' => 'Antolín del Campo'));
		Municipio::create(array('id' => 272, 'estado_id' => 16, 'municipio' => 'Arismendi'));
		Municipio::create(array('id' => 273, 'estado_id' => 16, 'municipio' => 'García'));
		Municipio::create(array('id' => 274, 'estado_id' => 16, 'municipio' => 'Gómez'));
		Municipio::create(array('id' => 275, 'estado_id' => 16, 'municipio' => 'Maneiro'));
		Municipio::create(array('id' => 276, 'estado_id' => 16, 'municipio' => 'Marcano'));
		Municipio::create(array('id' => 277, 'estado_id' => 16, 'municipio' => 'Mariño'));
		Municipio::create(array('id' => 278, 'estado_id' => 16, 'municipio' => 'Península de Macanao'));
		Municipio::create(array('id' => 279, 'estado_id' => 16, 'municipio' => 'Tubores'));
		Municipio::create(array('id' => 280, 'estado_id' => 16, 'municipio' => 'Villalba'));
		Municipio::create(array('id' => 281, 'estado_id' => 16, 'municipio' => 'Díaz'));
		Municipio::create(array('id' => 282, 'estado_id' => 17, 'municipio' => 'Agua Blanca'));
		Municipio::create(array('id' => 283, 'estado_id' => 17, 'municipio' => 'Araure'));
		Municipio::create(array('id' => 284, 'estado_id' => 17, 'municipio' => 'Esteller'));
		Municipio::create(array('id' => 285, 'estado_id' => 17, 'municipio' => 'Guanare'));
		Municipio::create(array('id' => 286, 'estado_id' => 17, 'municipio' => 'Guanarito'));
		Municipio::create(array('id' => 287, 'estado_id' => 17, 'municipio' => 'Monseñor José Vicente de Unda'));
		Municipio::create(array('id' => 288, 'estado_id' => 17, 'municipio' => 'Ospino'));
		Municipio::create(array('id' => 289, 'estado_id' => 17, 'municipio' => 'Páez'));
		Municipio::create(array('id' => 290, 'estado_id' => 17, 'municipio' => 'Papelón'));
		Municipio::create(array('id' => 291, 'estado_id' => 17, 'municipio' => 'San Genaro de Boconoíto'));
		Municipio::create(array('id' => 292, 'estado_id' => 17, 'municipio' => 'San Rafael de Onoto'));
		Municipio::create(array('id' => 293, 'estado_id' => 17, 'municipio' => 'Santa Rosalía'));
		Municipio::create(array('id' => 294, 'estado_id' => 17, 'municipio' => 'Sucre'));
		Municipio::create(array('id' => 295, 'estado_id' => 17, 'municipio' => 'Turén'));
		Municipio::create(array('id' => 296, 'estado_id' => 18, 'municipio' => 'Andrés Eloy Blanco'));
		Municipio::create(array('id' => 297, 'estado_id' => 18, 'municipio' => 'Andrés Mata'));
		Municipio::create(array('id' => 298, 'estado_id' => 18, 'municipio' => 'Arismendi'));
		Municipio::create(array('id' => 299, 'estado_id' => 18, 'municipio' => 'Benítez'));
		Municipio::create(array('id' => 300, 'estado_id' => 18, 'municipio' => 'Bermúdez'));
		Municipio::create(array('id' => 301, 'estado_id' => 18, 'municipio' => 'Bolívar'));
		Municipio::create(array('id' => 302, 'estado_id' => 18, 'municipio' => 'Cajigal'));
		Municipio::create(array('id' => 303, 'estado_id' => 18, 'municipio' => 'Cruz Salmerón Acosta'));
		Municipio::create(array('id' => 304, 'estado_id' => 18, 'municipio' => 'Libertador'));
		Municipio::create(array('id' => 305, 'estado_id' => 18, 'municipio' => 'Mariño'));
		Municipio::create(array('id' => 306, 'estado_id' => 18, 'municipio' => 'Mejía'));
		Municipio::create(array('id' => 307, 'estado_id' => 18, 'municipio' => 'Montes'));
		Municipio::create(array('id' => 308, 'estado_id' => 18, 'municipio' => 'Ribero'));
		Municipio::create(array('id' => 309, 'estado_id' => 18, 'municipio' => 'Sucre'));
		Municipio::create(array('id' => 310, 'estado_id' => 18, 'municipio' => 'Valdéz'));
		Municipio::create(array('id' => 341, 'estado_id' => 19, 'municipio' => 'Andrés Bello'));
		Municipio::create(array('id' => 342, 'estado_id' => 19, 'municipio' => 'Antonio Rómulo Costa'));
		Municipio::create(array('id' => 343, 'estado_id' => 19, 'municipio' => 'Ayacucho'));
		Municipio::create(array('id' => 344, 'estado_id' => 19, 'municipio' => 'Bolívar'));
		Municipio::create(array('id' => 345, 'estado_id' => 19, 'municipio' => 'Cárdenas'));
		Municipio::create(array('id' => 346, 'estado_id' => 19, 'municipio' => 'Córdoba'));
		Municipio::create(array('id' => 347, 'estado_id' => 19, 'municipio' => 'Fernández Feo'));
		Municipio::create(array('id' => 348, 'estado_id' => 19, 'municipio' => 'Francisco de Miranda'));
		Municipio::create(array('id' => 349, 'estado_id' => 19, 'municipio' => 'García de Hevia'));
		Municipio::create(array('id' => 350, 'estado_id' => 19, 'municipio' => 'Guásimos'));
		Municipio::create(array('id' => 351, 'estado_id' => 19, 'municipio' => 'Independencia'));
		Municipio::create(array('id' => 352, 'estado_id' => 19, 'municipio' => 'Jáuregui'));
		Municipio::create(array('id' => 353, 'estado_id' => 19, 'municipio' => 'José María Vargas'));
		Municipio::create(array('id' => 354, 'estado_id' => 19, 'municipio' => 'Junín'));
		Municipio::create(array('id' => 355, 'estado_id' => 19, 'municipio' => 'Libertad'));
		Municipio::create(array('id' => 356, 'estado_id' => 19, 'municipio' => 'Libertador'));
		Municipio::create(array('id' => 357, 'estado_id' => 19, 'municipio' => 'Lobatera'));
		Municipio::create(array('id' => 358, 'estado_id' => 19, 'municipio' => 'Michelena'));
		Municipio::create(array('id' => 359, 'estado_id' => 19, 'municipio' => 'Panamericano'));
		Municipio::create(array('id' => 360, 'estado_id' => 19, 'municipio' => 'Pedro María Ureña'));
		Municipio::create(array('id' => 361, 'estado_id' => 19, 'municipio' => 'Rafael Urdaneta'));
		Municipio::create(array('id' => 362, 'estado_id' => 19, 'municipio' => 'Samuel Darío Maldonado'));
		Municipio::create(array('id' => 363, 'estado_id' => 19, 'municipio' => 'San Cristóbal'));
		Municipio::create(array('id' => 364, 'estado_id' => 19, 'municipio' => 'Seboruco'));
		Municipio::create(array('id' => 365, 'estado_id' => 19, 'municipio' => 'Simón Rodríguez'));
		Municipio::create(array('id' => 366, 'estado_id' => 19, 'municipio' => 'Sucre'));
		Municipio::create(array('id' => 367, 'estado_id' => 19, 'municipio' => 'Torbes'));
		Municipio::create(array('id' => 368, 'estado_id' => 19, 'municipio' => 'Uribante'));
		Municipio::create(array('id' => 369, 'estado_id' => 19, 'municipio' => 'San Judas Tadeo'));
		Municipio::create(array('id' => 370, 'estado_id' => 20, 'municipio' => 'Andrés Bello'));
		Municipio::create(array('id' => 371, 'estado_id' => 20, 'municipio' => 'Boconó'));
		Municipio::create(array('id' => 372, 'estado_id' => 20, 'municipio' => 'Bolívar'));
		Municipio::create(array('id' => 373, 'estado_id' => 20, 'municipio' => 'Candelaria'));
		Municipio::create(array('id' => 374, 'estado_id' => 20, 'municipio' => 'Carache'));
		Municipio::create(array('id' => 375, 'estado_id' => 20, 'municipio' => 'Escuque'));
		Municipio::create(array('id' => 376, 'estado_id' => 20, 'municipio' => 'José Felipe Márquez Cañizalez'));
		Municipio::create(array('id' => 377, 'estado_id' => 20, 'municipio' => 'Juan Vicente Campos Elías'));
		Municipio::create(array('id' => 378, 'estado_id' => 20, 'municipio' => 'La Ceiba'));
		Municipio::create(array('id' => 379, 'estado_id' => 20, 'municipio' => 'Miranda'));
		Municipio::create(array('id' => 380, 'estado_id' => 20, 'municipio' => 'Monte Carmelo'));
		Municipio::create(array('id' => 381, 'estado_id' => 20, 'municipio' => 'Motatán'));
		Municipio::create(array('id' => 382, 'estado_id' => 20, 'municipio' => 'Pampán'));
		Municipio::create(array('id' => 383, 'estado_id' => 20, 'municipio' => 'Pampanito'));
		Municipio::create(array('id' => 384, 'estado_id' => 20, 'municipio' => 'Rafael Rangel'));
		Municipio::create(array('id' => 385, 'estado_id' => 20, 'municipio' => 'San Rafael de Carvajal'));
		Municipio::create(array('id' => 386, 'estado_id' => 20, 'municipio' => 'Sucre'));
		Municipio::create(array('id' => 387, 'estado_id' => 20, 'municipio' => 'Trujillo'));
		Municipio::create(array('id' => 388, 'estado_id' => 20, 'municipio' => 'Urdaneta'));
		Municipio::create(array('id' => 389, 'estado_id' => 20, 'municipio' => 'Valera'));
		Municipio::create(array('id' => 390, 'estado_id' => 21, 'municipio' => 'Vargas'));
		Municipio::create(array('id' => 391, 'estado_id' => 22, 'municipio' => 'Arístides Bastidas'));
		Municipio::create(array('id' => 392, 'estado_id' => 22, 'municipio' => 'Bolívar'));
		Municipio::create(array('id' => 407, 'estado_id' => 22, 'municipio' => 'Bruzual'));
		Municipio::create(array('id' => 408, 'estado_id' => 22, 'municipio' => 'Cocorote'));
		Municipio::create(array('id' => 409, 'estado_id' => 22, 'municipio' => 'Independencia'));
		Municipio::create(array('id' => 410, 'estado_id' => 22, 'municipio' => 'José Antonio Páez'));
		Municipio::create(array('id' => 411, 'estado_id' => 22, 'municipio' => 'La Trinidad'));
		Municipio::create(array('id' => 412, 'estado_id' => 22, 'municipio' => 'Manuel Monge'));
		Municipio::create(array('id' => 413, 'estado_id' => 22, 'municipio' => 'Nirgua'));
		Municipio::create(array('id' => 414, 'estado_id' => 22, 'municipio' => 'Peña'));
		Municipio::create(array('id' => 415, 'estado_id' => 22, 'municipio' => 'San Felipe'));
		Municipio::create(array('id' => 416, 'estado_id' => 22, 'municipio' => 'Sucre'));
		Municipio::create(array('id' => 417, 'estado_id' => 22, 'municipio' => 'Urachiche'));
		Municipio::create(array('id' => 418, 'estado_id' => 22, 'municipio' => 'José Joaquín Veroes'));
		Municipio::create(array('id' => 441, 'estado_id' => 23, 'municipio' => 'Almirante Padilla'));
		Municipio::create(array('id' => 442, 'estado_id' => 23, 'municipio' => 'Baralt'));
		Municipio::create(array('id' => 443, 'estado_id' => 23, 'municipio' => 'Cabimas'));
		Municipio::create(array('id' => 444, 'estado_id' => 23, 'municipio' => 'Catatumbo'));
		Municipio::create(array('id' => 445, 'estado_id' => 23, 'municipio' => 'Colón'));
		Municipio::create(array('id' => 446, 'estado_id' => 23, 'municipio' => 'Francisco Javier Pulgar'));
		Municipio::create(array('id' => 447, 'estado_id' => 23, 'municipio' => 'Páez'));
		Municipio::create(array('id' => 448, 'estado_id' => 23, 'municipio' => 'Jesús Enrique Losada'));
		Municipio::create(array('id' => 449, 'estado_id' => 23, 'municipio' => 'Jesús María Semprún'));
		Municipio::create(array('id' => 450, 'estado_id' => 23, 'municipio' => 'La Cañada de Urdaneta'));
		Municipio::create(array('id' => 451, 'estado_id' => 23, 'municipio' => 'Lagunillas'));
		Municipio::create(array('id' => 452, 'estado_id' => 23, 'municipio' => 'Machiques de Perijá'));
		Municipio::create(array('id' => 453, 'estado_id' => 23, 'municipio' => 'Mara'));
		Municipio::create(array('id' => 454, 'estado_id' => 23, 'municipio' => 'Maracaibo'));
		Municipio::create(array('id' => 455, 'estado_id' => 23, 'municipio' => 'Miranda'));
		Municipio::create(array('id' => 456, 'estado_id' => 23, 'municipio' => 'Rosario de Perijá'));
		Municipio::create(array('id' => 457, 'estado_id' => 23, 'municipio' => 'San Francisco'));
		Municipio::create(array('id' => 458, 'estado_id' => 23, 'municipio' => 'Santa Rita'));
		Municipio::create(array('id' => 459, 'estado_id' => 23, 'municipio' => 'Simón Bolívar'));
		Municipio::create(array('id' => 460, 'estado_id' => 23, 'municipio' => 'Sucre'));
		Municipio::create(array('id' => 461, 'estado_id' => 23, 'municipio' => 'Valmore Rodríguez'));
		Municipio::create(array('id' => 462, 'estado_id' => 24, 'municipio' => 'Libertador'));
	}
}
